# Telegraf configuration for the UTM test environment.

[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "utm-test"
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "utm"
  skip_database_creation = true
  timeout = "5s"

[[inputs.exec]]
  commands = [
    "python3 /utm/ucs_traffic_monitor.py influxdb-lp --instance-name utm -vv"
  ]
  timeout = "50s"
  data_format = "influx"
  name_suffix = ""
