{
 "title": "Chassis PAUSE frame monitoring",
 "tags": [
  "cisco",
  "UCS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "Database", "query": "telegraf" },
   { "name": "rp", "label": "Retention Policy", "query": "autogen" },
   { "name": "data_source", "label": "Data Source", "query": "influxdb" },
   {
    "name": "domain",
    "label": "UCS Domain",
    "query": "show tag values from \"$db\".\"$rp\".\"FIEnvStats\" with key=domain where $timeFilter"
   },
   { "name": "fi_id", "label": "FI ID (A or B)", "query": "A,B" },
   {
    "name": "server_port",
    "label": "Server Port",
    "query": "show tag values from \"$db\".\"$rp\".\"FIServerPortStats\" with key=port where domain =~ /${domain:regex}/ and fi_id =~ /${fi_id:regex}/ and channel != '' and $timeFilter"
   },
   {
    "name": "chassis",
    "label": "Chassis",
    "query": "show tag values from \"$db\".\"$rp\".\"FIServerPortStats\" with key=peer where domain =~ /${domain:regex}/ and fi_id =~ /${fi_id:regex}/ and port =~ /${server_port:regex}/ and  $timeFilter"
   },
   {
    "name": "bp_port",
    "label": "Backplane Port",
    "query": "show tag values from \"$db\".\"$rp\".\"BackplanePortStats\" with key=bp_port where domain =~ /${domain:regex}/ and fi_id =~ /${fi_id:regex}/ and chassis =~ /${chassis:regex}/ and channel != ''  and $timeFilter"
   },
   { "name": "polling_interval", "query": "60" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"margin: 0px; padding: 0px; border: 1px; border-collapse: collapse;\" width=\"100%\">\n<tbody>\n<tr style=\"margin: 0px; padding: 0px;\">\n<td style=\"width: 15%; margin: 0px; padding: 0px; border: none;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/utm/cisco_logo.png' width=\"120\" />\n</td>\n<td style=\"width: 70%; margin: 0px; padding: 0px; border: none;\">\n<h2 style=\"text-align: center; margin: 2px;\"><span style=\"color: #0085FC;\"><strong>UTM - UCS Traffic Monitoring</strong></span></h2>\n</td>\n<td style=\"width: 15%; margin: 0px; border: none;\" valign=\"middle\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/utm/your_logo.png' alt=\"\" width=\"120\"/>\n</td>\n</tr>\n</tbody>\n</table>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 2 },
   "options": {
    "content": "[Locations](/d/ri2OFp4Wz/locations) | [Domain Overview](/d/Inte2EIWk/ucs-domain-overview) | [Domain Traffic](/d/W7LSukHWz/ucs-domain-traffic) | [Chassis Traffic](/d/KOM8ZHNWz/ucs-chassis-traffic) | [Servers](/d/Z0M_N1vWz/service-profile-stats) | [Ingress Congestion](/d/Sve32sDZk/fi-uplink-port-ingress-congestion-monitoring)"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "options": {
    "content": "[detailed_congestion](/d/SVO-VNiWk/chassis-pause-frame-monitoring)"
   }
  },
  {
   "type": "text",
   "description": "Find Congestion on any link within a UCS Domain",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "options": {
    "content": "\n<h2 style=\"text-align: center;\"><span style=\"color: #0085FC;\"><strong>Detail Congestion Monitoring - <span style=\"color: #ff00ff;\">$domain</span></strong></h2>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PAUSE frame monitoring on FI server ports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 6 },
   "options": {
    "content": "<h2 style=\"text-align: center;\">Congestion against <span style=\"color: #00ff00;\">Ingress</span> traffic</h2>"
   },
   "content": "<h1 style=\"text-align: center;\">Congestion against inbound traffic</h1>",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 6 },
   "options": {
    "content": "<h2 style=\"text-align: center;\">Congestion against <span style=\"color: #00ffff;\">Egress</span> traffic</h2>"
   },
   "content": "<h1 style=\"text-align: center;\">Congestion against outbound traffic</h1>",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FI-A - Server port - RX PAUSE monitoring",
   "type": "graph",
   "description": "**Use Case**: Monitor congestion against ingress traffic on FI Server Ports. \n\n![Server Ports RX PAUSE](/public/img/utm/fi_server_port_rx_pause.png)\n\n**How to use**:  Select a UCS domain and FI Server Port (s). The graphs display RX PAUSE received on the FI Server Ports. These PAUSE frames are sent by the connected devices (FEX, IOM or Servers) when they must apply backpressure on the incoming traffic. *Note*: Server Ingress traffic is TX for FI Server Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect FI Server port with unusual PAUSE frame activity, the next step depends on the type of connected device.\n-\tIf the connected device is a server, you have found the ultimate traffic destination or Congestion source.\n-\tIf the connected device is a FEX or IOM in a chassis, monitor the congestion on the backplane ports to find the (blade) server (s).\n**Details**: \n- A server sends PAUSE frames if it is unable to receive the traffic at the ingress rate. These frames are reported as RX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col on $tag_port from $tag_peer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "peer_chassis" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "SELECT non_negative_difference(mean(\"pause_rx\"))  / [[polling_interval]] AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" = 'A' AND \"port\" =~ /^${server_port:regex}$/) AND $timeFilter GROUP BY time($__interval), \"port\", \"peer\" fill(linear)",
     "select": [
      [
       { "params": [ "pause_rx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / [[polling_interval]]" ], "type": "math" },
       { "params": [ "RX PAUSE" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" },
      { "condition": "AND", "key": "port", "operator": "=~", "value": "/^$server_port$/" }
     ]
    }
   ]
  },
  {
   "title": "FI-A - Server port - TX PAUSE monitoring",
   "type": "graph",
   "description": "**Use Case**: Monitor congestion against egress traffic on FI Server Ports. \n\n![Server Ports TX PAUSE](/public/img/utm/fi_server_port_tx_pause.png)\n\n**How to use**:  Select a UCS domain and FI Server Port (s). The graphs display TX PAUSE sent by the FI Server Ports. These PAUSE frames are sent to the connected devices (FEX, IOM or Servers) when the backpressure must be applied against the outgoing traffic. *Note*: Server Egress traffic is RX for FI Server Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect FI Server port with unusual PAUSE frame activity, the next step depends on the type of connected device.\n-\tIf the connected device is a server, you have found the ultimate traffic destination or Congestion source.\n-\tIf the connected device is a FEX or IOM in a chassis, monitor the congestion on the backplane ports to find the (blade) server (s).\n**Details**: \n- A server receives PAUSE frames if it is transmitting data faster than the receiver can accept it. These frames are reported as TX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col on $tag_port to $tag_peer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "peer_chassis" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "SELECT non_negative_difference(mean(\"pause_tx\"))  / [[polling_interval]] AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" = 'A' AND \"port\" =~ /^${server_port:regex}$/) AND $timeFilter GROUP BY time($__interval), \"port\", \"peer\" fill(linear)",
     "select": [
      [
       { "params": [ "pause_tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / [[polling_interval]]" ], "type": "math" },
       { "params": [ "TX PAUSE" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" },
      { "condition": "AND", "key": "port", "operator": "=~", "value": "/^$server_port$/" }
     ]
    }
   ]
  },
  {
   "title": "FI-B - Server port - RX PAUSE monitoring",
   "type": "graph",
   "description": "**Use Case**: Monitor congestion against ingress traffic on FI Server Ports. \n\n![Server Ports RX PAUSE](/public/img/utm/fi_server_port_rx_pause.png)\n\n**How to use**:  Select a UCS domain and FI Server Port (s). The graphs display RX PAUSE received on the FI Server Ports. These PAUSE frames are sent by the connected devices (FEX, IOM or Servers) when they must apply backpressure on the incoming traffic. *Note*: Server Ingress traffic is TX for FI Server Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect FI Server port with unusual PAUSE frame activity, the next step depends on the type of connected device.\n-\tIf the connected device is a server, you have found the ultimate traffic destination or Congestion source.\n-\tIf the connected device is a FEX or IOM in a chassis, monitor the congestion on the backplane ports to find the (blade) server (s).\n**Details**: \n- A server sends PAUSE frames if it is unable to receive the traffic at the ingress rate. These frames are reported as RX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col on $tag_port from $tag_peer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "peer_chassis" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "SELECT non_negative_difference(mean(\"pause_rx\"))  / [[polling_interval]] AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" = 'B' AND \"port\" =~ /^${server_port:regex}$/) AND $timeFilter GROUP BY time($__interval), \"port\", \"peer\" fill(linear)",
     "select": [
      [
       { "params": [ "pause_rx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / [[polling_interval]]" ], "type": "math" },
       { "params": [ "RX PAUSE" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" },
      { "condition": "AND", "key": "port", "operator": "=~", "value": "/^$server_port$/" }
     ]
    }
   ]
  },
  {
   "title": "FI-B - Server port - TX PAUSE monitoring",
   "type": "graph",
   "description": "**Use Case**: Monitor congestion against egress traffic on FI Server Ports. \n\n![Server Ports TX PAUSE](/public/img/utm/fi_server_port_tx_pause.png)\n\n**How to use**:  Select a UCS domain and FI Server Port (s). The graphs display TX PAUSE sent by the FI Server Ports. These PAUSE frames are sent to the connected devices (FEX, IOM or Servers) when the backpressure must be applied against the outgoing traffic. *Note*: Server Egress traffic is RX for FI Server Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect FI Server port with unusual PAUSE frame activity, the next step depends on the type of connected device.\n-\tIf the connected device is a server, you have found the ultimate traffic destination or Congestion source.\n-\tIf the connected device is a FEX or IOM in a chassis, monitor the congestion on the backplane ports to find the (blade) server (s).\n**Details**: \n- A server receives PAUSE frames if it is transmitting data faster than the receiver can accept it. These frames are reported as TX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col on $tag_port to $tag_peer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "peer_chassis" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "SELECT non_negative_difference(mean(\"pause_tx\"))  / [[polling_interval]] AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" = 'B' AND \"port\" =~ /^${server_port:regex}$/) AND $timeFilter GROUP BY time($__interval), \"port\", \"peer\" fill(linear)",
     "select": [
      [
       { "params": [ "pause_tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / [[polling_interval]]" ], "type": "math" },
       { "params": [ "TX PAUSE" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" },
      { "condition": "AND", "key": "port", "operator": "=~", "value": "/^$server_port$/" }
     ]
    }
   ]
  },
  {
   "title": "PAUSE frame monitoring on Backplane Ports in $chassis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "chassis",
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 7 },
     "options": {
      "content": "<h2 style=\"text-align: center;\">Congestion against <span style=\"color: #00ff00;\">Ingress</span> traffic</h2>"
     },
     "content": "<h1 style=\"text-align: center;\">Congestion against inbound traffic</h1>",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 7 },
     "options": {
      "content": "<h2 style=\"text-align: center;\">Congestion against <span style=\"color: #00ffff;\">Egress</span> traffic</h2>"
     },
     "content": "<h1 style=\"text-align: center;\">Congestion against outbound traffic</h1>",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backplane port RX PAUSE stats in $chassis via FI-A",
     "type": "graph",
     "description": "**Use Case**: Monitor congestion against ingress traffic on FEX/IOM Backplane Ports. \n\n![Server Ports RX PAUSE](/public/img/utm/backplane_port_rx_pause.png)\n\n**How to use**:  Select a UCS domain and Chassis. The graphs display RX PAUSE received on the FEX/IOM Backplane Ports. These PAUSE frames are sent by the connected servers when they must apply backpressure on the incoming traffic. *Note*: Server Ingress traffic is TX for Backplane Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\n**Details**: \n- A server sends PAUSE frames if it is unable to receive the traffic at the ingress rate. These frames are reported as RX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col on $tag_bp_port from $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "peer_service_profile" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(mean(\"pause_rx\"))  / [[polling_interval]] AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" = 'A' AND \"chassis\" =~ /^${chassis:regex}$/) AND $timeFilter GROUP BY time($__interval), \"chassis\", \"bp_port\", \"peer_service_profile\" fill(null)",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" }
       ]
      }
     ]
    },
    {
     "title": "Backplane port TX PAUSE stats in $chassis via FI-A",
     "type": "graph",
     "description": "**Use Case**: Monitor congestion against egress traffic on FEX/IOM Backplane Ports. \n\n![Server Ports RX PAUSE](/public/img/utm/backplane_port_tx_pause.png)\n\n**How to use**:  Select a UCS domain and Chassis. The graphs display TX PAUSE sent by the FEX/IOM Backplane Ports. These PAUSE frames are sent to the connected servers when the backpressure must be applied against the outgoing traffic. *Note*: Server Egress traffic is RX for Backplane Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\n**Details**: \n- A server receives PAUSE frames if it is transmitting data faster than the receiver can accept it. These frames are reported as TX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col on $tag_bp_port to $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "peer_service_profile" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(mean(\"pause_tx\"))  / [[polling_interval]] AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" = 'A' AND \"chassis\" =~ /^${chassis:regex}$/) AND $timeFilter GROUP BY time($__interval), \"chassis\", \"bp_port\", \"peer_service_profile\" fill(null)",
       "select": [
        [
         { "params": [ "pause_tx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "TX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" }
       ]
      }
     ]
    },
    {
     "title": "Backplane port RX PAUSE stats in $chassis via FI-B",
     "type": "graph",
     "description": "**Use Case**: Monitor congestion against ingress traffic on FEX/IOM Backplane Ports. \n\n![Server Ports RX PAUSE](/public/img/utm/backplane_port_rx_pause.png)\n\n**How to use**:  Select a UCS domain and Chassis. The graphs display RX PAUSE received on the FEX/IOM Backplane Ports. These PAUSE frames are sent by the connected servers when they must apply backpressure on the incoming traffic. *Note*: Server Ingress traffic is TX for Backplane Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\n**Details**: \n- A server sends PAUSE frames if it is unable to receive the traffic at the ingress rate. These frames are reported as RX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col on $tag_bp_port from $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "peer_service_profile" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(mean(\"pause_rx\"))  / [[polling_interval]] AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" = 'B' AND \"chassis\" =~ /^${chassis:regex}$/) AND $timeFilter GROUP BY time($__interval), \"chassis\", \"bp_port\", \"peer_service_profile\" fill(null)",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" }
       ]
      }
     ]
    },
    {
     "title": "Backplane port RX PAUSE stats in $chassis via FI-B",
     "type": "graph",
     "description": "**Use Case**: Monitor congestion against egress traffic on FEX/IOM Backplane Ports. \n\n![Server Ports RX PAUSE](/public/img/utm/backplane_port_tx_pause.png)\n\n**How to use**:  Select a UCS domain and Chassis. The graphs display TX PAUSE sent by the FEX/IOM Backplane Ports. These PAUSE frames are sent to the connected servers when the backpressure must be applied against the outgoing traffic. *Note*: Server Egress traffic is RX for Backplane Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\n**Details**: \n- A server receives PAUSE frames if it is transmitting data faster than the receiver can accept it. These frames are reported as TX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col on $tag_bp_port to $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "peer_service_profile" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(mean(\"pause_tx\"))  / [[polling_interval]] AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" = 'B' AND \"chassis\" =~ /^${chassis:regex}$/) AND $timeFilter GROUP BY time($__interval), \"chassis\", \"bp_port\", \"peer_service_profile\" fill(null)",
       "select": [
        [
         { "params": [ "pause_tx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "TX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress Traffic Congestion in $chassis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "chassis",
   "collapsed": true,
   "panels": [
    {
     "title": "RX PAUSE on Backplane port $bp_port in $chassis",
     "type": "graph",
     "description": "**Use Case**: Find the root cause of ingress traffic congestion. \n\n![](/public/img/utm/chassis_ingress_congestion.png)\n\n**How to use**:  Select a UCS domain, chassis, and Backplane Port. One row is created per chassis. Graphs are generated for backplanes ports in that chassis within the row. Choose one Chassis at a time if you have many chassis. \n\nFI and FEX/IOM ports do not originate or terminate the traffic. Mostly, the real cause of congestion is one of the servers which is unable to receive traffic at the incoming rate. Try to find one of those servers by comparing unusual PAUSE frame activity and traffic spikes. Refer to the graphs on the left with RX PAUSE frames on IOM/FEX backplane ports which indicate a backpressure applied by Server against ingress traffic.  PAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect backplane port with unusual PAUSE frame activity, look at the graph on the right which shows the service profile and vNIC/vHBA traffic using that backplane port. High traffic rate or traffic spikes, especially with matching timestamp with unusual PAUSE frame activity, indicate that high utilization is the cause of congestion.\n\n**Details**: \n- A server sends PAUSE frames to IOM/FEX backplane port if it is unable to receive the traffic at the ingress rate. These frames are reported as RX PAUSE on IOM/FEX backplane ports. \n- PAUSE frames are not reported at per vNIC/vHBA granularity. \n- PAUSE frames are used by FC traffic (no-drop class) only. Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "repeat": "bp_port",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col <-- $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "domain" ], "type": "tag" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(mean(\"pause_rx\"))  / [[polling_interval]] AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" =~ /^${fi_id:regex}$/ AND \"chassis\" =~ /^${chassis:regex}$/ AND \"bp_port\" =~ /^${bp_port:regex}$/) AND $timeFilter GROUP BY time($__interval), \"domain\", \"chassis\", \"bp_port\",\"peer_service_profile\" fill(null)",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "RX Traffic to vIFs from Backplane port $bp_port in $chassis",
     "type": "graph",
     "description": "Refer to the description of the panel on the left. Compare high PAUSE frame activity from the left graph to the high traffic activity in this graph.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "repeat": "bp_port",
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_profile $tag_vif_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "service_profile" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT mean(\"bytes_rx_delta\")  *8/[[polling_interval]] AS \"RX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" =~ /^${fi_id:regex}$/ AND \"chassis\" =~ /^${chassis:regex}$/ AND \"peer_port\" =~ /^${bp_port:regex}$/) AND $timeFilter GROUP BY time($__interval), \"vif_name\", \"service_profile\" fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *8/[[polling_interval]]" ], "type": "math" },
         { "params": [ "RX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Egress Traffic Congestion in $chassis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "repeat": "chassis",
   "collapsed": true,
   "panels": [
    {
     "title": "TX PAUSE on Backplane port $bp_port in $chassis",
     "type": "graph",
     "description": "**Use Case**: Find the root cause of egress traffic congestion. \n\n![](/public/img/utm/chassis_egress_congestion.png)\n\n**How to use**:  Select a UCS domain, chassis, and Backplane Port. One row is created per chassis. Graphs are generated for backplanes ports in that chassis within the row. Choose one Chassis at a time if you have many chassis. \n\nFI and FEX/IOM ports do not originate or terminate the traffic. Mostly, the real cause of congestion is one of the servers which is unable to sending data faster than the receiver can ingest it. Try to find one of those servers by comparing unusual PAUSE frame activity and traffic spikes. Refer to the graphs on the left with TX PAUSE frames on IOM/FEX backplane ports which indicate a backpressure applied to Servers against egress traffic.  PAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect backplane port with unusual PAUSE frame activity, look at the graph on the right which shows the service profile and vNIC/vHBA traffic using that backplane port. High traffic rate or traffic spikes, especially with matching timestamp with unusual PAUSE frame activity, indicate that high utilization is the cause of congestion.\n\n**Details**: \n- A server receives PAUSE frames if it is transmitting data faster than the receiver can accept it. These frames are reported as TX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are not reported at per vNIC/vHBA granularity. \n- PAUSE frames are used by FC traffic (no-drop class) only. Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col --> $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "domain" ], "type": "tag" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(mean(\"pause_tx\"))  / [[polling_interval]] AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" =~ /^${fi_id:regex}$/ AND \"chassis\" =~ /^${chassis:regex}$/ AND \"bp_port\" =~ /^${bp_port:regex}$/) AND $timeFilter GROUP BY time($__interval), \"domain\", \"chassis\", \"bp_port\",\"peer_service_profile\" fill(null)",
       "select": [
        [
         { "params": [ "pause_tx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "TX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "TX Traffic from vIFs to Backplane port $bp_port in $chassis",
     "type": "graph",
     "description": "Refer to the description of the panel on the left. Compare high PAUSE frame activity from the left graph to the high traffic activity in this graph.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_profile $tag_vif_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "service_profile" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT mean(\"bytes_tx_delta\")  *8/[[polling_interval]] AS \"TX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" =~ /^${fi_id:regex}$/ AND \"chassis\" =~ /^${chassis:regex}$/ AND \"peer_port\" =~ /^${bp_port:regex}$/) AND $timeFilter GROUP BY time($__interval), \"vif_name\", \"service_profile\" fill(linear)",
       "select": [
        [
         { "params": [ "bytes_tx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *8/[[polling_interval]]" ], "type": "math" },
         { "params": [ "TX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}