{
 "title": "UCS Domain - Overview",
 "tags": [
  "cisco",
  "UCS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "Database", "query": "telegraf" },
   { "name": "rp", "label": "Retention Policy", "query": "autogen" },
   { "name": "data_source", "label": "Data Source", "query": "influxdb" },
   { "name": "polling_interval", "query": "60" },
   {
    "name": "domain",
    "label": "UCS Domain",
    "query": "show tag values from \"$db\".\"$rp\".\"FIEnvStats\" with key=domain where $timeFilter"
   },
   { "name": "5m_in_ms", "query": "300000" },
   {
    "name": "utm_collector_ver",
    "query": "select last(utm_collector_ver) from \"$db\".\"$rp\".\"FIEnvStats\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "![Cisco UCS Architecture](/public/img/utm/ucs_architecture.png)\nUTM collector - v$utm_collector_ver  \nUTM GUI - v0.52  \nby Paresh Gupta",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"margin: 0px; padding: 0px; border: 1px; border-collapse: collapse;\" width=\"100%\">\n<tbody>\n<tr style=\"margin: 0px; padding: 0px;\">\n<td style=\"width: 15%; margin: 0px; padding: 0px; border: none;\" valign=\"middle\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/utm/cisco_logo.png' width=\"120\" />\n</td>\n<td style=\"width: 70%; margin: 0px; padding: 0px; border: none;\">\n<h2 style=\"text-align: center; margin: 2px;\"><span style=\"color: #0085FC;\"><strong>UTM - UCS Traffic Monitoring</strong></span></h2>\n</td>\n<td style=\"width: 15%; margin: 0px; border: none;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/utm/your_logo.png' alt=\"\" width=\"120\"/>\n</td>\n</tr>\n</tbody>\n</table>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "[Locations](/d/ri2OFp4Wz/locations?from=${__from}&to=${__to}&var-domain=${domain}) | [Domain Overview](/d/Inte2EIWk/ucs-domain-overview?from=${__from}&to=${__to}&var-domain=${domain}) | [Domain Traffic](/d/W7LSukHWz/ucs-domain-traffic?from=${__from}&to=${__to}&var-domain=${domain}) | [Chassis Traffic](/d/KOM8ZHNWz/ucs-chassis-traffic?from=${__from}&to=${__to}&var-domain=${domain}) | [Servers](/d/Z0M_N1vWz/service-profile-stats?from=${__from}&to=${__to}&var-domain=${domain}) | [Ingress Congestion](/d/Sve32sDZk/fi-uplink-port-ingress-congestion-monitoring?from=${__from}&to=${__to}&var-domain=${domain})"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "\n<h2 style=\"text-align: center;\"><span style=\"color: #0085FC;\"><strong>UCS Domain Overview - </span><span style=\"color: #ff00ff;\"> $domain</span></strong></h2>\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UCS Domain Name - $domain",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "FIEnvStats",
     "query": "SELECT last(\"name\") FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^${domain:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime - $domain",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "FIEnvStats",
     "query": "SELECT last(\"sys_uptime\") AS \"Uptime\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^${domain:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sys_uptime" ], "type": "field" },
       { "params": [ "Uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU and Memory - $domain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select sum(last) as \"Memory\" from (SELECT last(\"memory\") FROM \"$db\".\"$rp\".\"Servers\" WHERE (\"domain\" =~ /^${domain:regex}$/) AND $timeFilter GROUP BY domain,chassis,server,id) where $timeFilter",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(last) as \"#CPU\" from (SELECT last(\"num_cpus\") FROM \"$db\".\"$rp\".\"Servers\" WHERE (\"domain\" =~ /^${domain:regex}$/) AND $timeFilter GROUP BY domain,chassis,server,id) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(last) as \"#Cores\" from (SELECT last(\"num_cores\") FROM \"$db\".\"$rp\".\"Servers\" WHERE (\"domain\" =~ /^${domain:regex}$/) AND $timeFilter GROUP BY domain,chassis,server,id) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Server Types - $domain",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(id) AS \"Blade Servers\" from (SELECT last(\"model\") FROM \"$db\".\"$rp\".\"Servers\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"type\" = 'blade') AND $timeFilter GROUP BY time($__interval),domain,chassis,server,id) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Number of servers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(id) AS \"Rack Servers\" from (SELECT last(\"model\") FROM \"$db\".\"$rp\".\"Servers\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"type\" = 'rack') AND $timeFilter GROUP BY time($__interval),domain,chassis,server,id) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Number of servers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Server Operational State - $domain",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(id) AS \"OK\" from (SELECT last(\"model\") FROM \"$db\".\"$rp\".\"Servers\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"oper_state\" = 'ok') AND $timeFilter GROUP BY time($__interval),domain,chassis,server,id) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "oper_state" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Operation state - UP" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "oper_state", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select count(id) AS \"Other\" from (SELECT last(\"model\") FROM \"$db\".\"$rp\".\"Servers\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"oper_state\" != 'ok') AND $timeFilter GROUP BY time($__interval),domain,chassis,server,id) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "oper_state" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Other" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "oper_state", "operator": "!=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "UCSM Version - $domain",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "FIEnvStats",
     "query": "SELECT last(\"ucsm_fw_ver\") AS \"UCSM version\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^${domain:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ucsm_fw_ver" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "UCSM version" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Location - $domain",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "query": "select location from (select location,last(model) from \"$db\".\"$rp\".\"FIEnvStats\" where  (\"domain\" =~ /^${domain:regex}$/) AND $timeFilter) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "title": "# vIF - $domain",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select sum(last) as \"#vFC\" from (SELECT last(\"num_vFCs\") FROM \"$db\".\"$rp\".\"Servers\" WHERE (\"domain\" =~ /^${domain:regex}$/) AND $timeFilter GROUP BY domain,chassis,server ,id) where $timeFilter",
     "select": [
      [
       { "params": [ "num_vFCs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(last) as \"#vEth\" from (SELECT last(\"num_vEths\") FROM \"$db\".\"$rp\".\"Servers\" WHERE (\"domain\" =~ /^${domain:regex}$/) AND $timeFilter GROUP BY domain,chassis,server,id) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Chassis - $domain",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "select sum(count) from (select count(distinct(chassis)) from (SELECT last(\"model\") FROM \"$db\".\"$rp\".\"Servers\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND chassis!='') AND $timeFilter GROUP BY service_profile,domain,chassis,id) group by domain) where $timeFilter",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Number of servers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "FI-A Leadership",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"leadership\") as \"leadership\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" = 'A') AND $timeFilter"
    }
   ]
  },
  {
   "title": "FI-B Leadership",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"leadership\") as \"leadership\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" = 'B') AND $timeFilter"
    }
   ]
  },
  {
   "title": "FI-A - $domain",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "FIEnvStats",
     "query": "SELECT last(\"oob_if_ip\") AS \"OOB IP Address\", last(\"serial\") AS \"Serial\", last(\"model\") AS \"Model\", last(\"fi_fw_sys_ver\") AS \"System Version\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" = 'A') AND $timeFilter",
     "select": [
      [
       { "params": [ "oob_if_ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "OOB IP Address" ], "type": "alias" }
      ],
      [
       { "params": [ "serial" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Serial" ], "type": "alias" }
      ],
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "fi_fw_sys_ver" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "System version" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" }
     ]
    }
   ]
  },
  {
   "title": "FI-A Load - $domain",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "query": "SELECT last(\"load\") AS \"Load\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" = 'A') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Load" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" }
     ]
    }
   ]
  },
  {
   "title": "FI-A Memory - $domain",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "SELECT last(\"total_memory\")  as \"Total\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" =~ /A/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Number of servers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"mem_available\") as \"Available\"  FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" =~ /A/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FI-A Memory - $domain",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "query": "SELECT (last(\"total_memory\") - last(\"mem_available\"))/last(\"total_memory\")*100 FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" =~ /A/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" }
     ]
    }
   ]
  },
  {
   "title": "FI-B Memory - $domain",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "query": "SELECT (last(\"total_memory\") - last(\"mem_available\"))/last(\"total_memory\")*100 FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" =~ /B/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" }
     ]
    }
   ]
  },
  {
   "title": "FI-B Memory - $domain",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "BladeServers",
     "query": "SELECT last(\"total_memory\")  as \"Total\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" =~ /B/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Number of servers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"mem_available\") as \"Available\"  FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" =~ /B/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FI-B Load - $domain",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "FI-$tag_fi_id $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "query": "SELECT last(\"load\") AS \"Load\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" = 'B') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Load" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" }
     ]
    }
   ]
  },
  {
   "title": "FI-B - $domain",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "FIEnvStats",
     "query": "SELECT last(\"oob_if_ip\") AS \"OOB IP Address\", last(\"serial\") AS \"Serial\", last(\"model\") AS \"Model\", last(\"fi_fw_sys_ver\") AS \"System Version\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"fi_id\" = 'B') AND $timeFilter",
     "select": [
      [
       { "params": [ "oob_if_ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "OOB IP Address" ], "type": "alias" }
      ],
      [
       { "params": [ "serial" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Serial" ], "type": "alias" }
      ],
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "fi_fw_sys_ver" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "System version" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" }
     ]
    }
   ]
  },
  {
   "title": "FI-A Uplink and Other Ports - $domain",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' and \"fi_id\" =~ /A/) and $timeFilter group by port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-B Uplink and Other Ports - $domain",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' and \"fi_id\" =~ /B/) and $timeFilter group by port)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A Uplink Ports - Operational State - $domain",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"UP\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'up' AND \"fi_id\" = 'A') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"SFP not present\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'sfp-not-present' AND \"fi_id\" = 'A') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Admin down\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'admin-down' AND \"fi_id\" = 'A') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Failed\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'failed' AND \"fi_id\" = 'A') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Link Down\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'link-down' AND \"fi_id\" = 'A') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A Uplink Ports - Transport - $domain",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"FC\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"transport\" = 'FC' AND \"fi_id\" = 'A' ) and $timeFilter group by time($__interval),domain,fi_id,port) where $timeFilter group by time($__interval) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Ethernet\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"transport\" = 'Eth' AND \"fi_id\" = 'A' ) and  $timeFilter group by time($__interval),domain,fi_id,port) where  $timeFilter group by time($__interval) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-B Uplink Ports - Operational State - $domain",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"UP\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'up' AND \"fi_id\" = 'B') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"SFP not present\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'sfp-not-present' AND \"fi_id\" = 'B') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Admin down\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'admin-down' AND \"fi_id\" = 'B') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Failed\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'failed' AND \"fi_id\" = 'B') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Link Down\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'link-down' AND \"fi_id\" = 'B') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-B Uplink Ports - Transport - $domain",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"FC\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"transport\" = 'FC' AND \"fi_id\" = 'B' ) and $timeFilter group by time($__interval),domain,fi_id,port) where $timeFilter group by time($__interval) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Ethernet\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"transport\" = 'Eth' AND \"fi_id\" = 'B' ) and  $timeFilter group by time($__interval),domain,fi_id,port) where  $timeFilter group by time($__interval) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A Uplink Ports - Eth Speed - $domain",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"1 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'A' AND  transport = 'Eth' AND \"oper_speed\" = 1) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"10 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'A' AND  transport = 'Eth' AND \"oper_speed\" = 10) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"40 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'A' AND  transport = 'Eth' AND \"oper_speed\" = 40) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"25 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'A' AND  transport = 'Eth' AND \"oper_speed\" = 25) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A Uplink Ports - FC Speed - $domain",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"4G\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND transport = 'FC' AND \"oper_speed\" = 4 AND \"fi_id\" = 'A' ) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"8G\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND  transport = 'FC' AND \"oper_speed\" = 8 AND \"fi_id\" = 'A' ) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"16G\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND  transport = 'FC' AND \"oper_speed\" = 16 AND \"fi_id\" = 'A' ) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"32G\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND  transport = 'FC' AND \"oper_speed\" = 32 AND \"fi_id\" = 'A' ) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-B Uplink Ports - Eth Speed  - $domain",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"1 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'B' AND  transport = 'Eth' AND \"oper_speed\" = 1) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"10 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'B' AND  transport = 'Eth' AND \"oper_speed\" = 10) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"40 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'B' AND  transport = 'Eth' AND \"oper_speed\" = 40) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"25 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'B' AND  transport = 'Eth' AND \"oper_speed\" = 25) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-B Uplink Ports - FC Speed - $domain",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"4G\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND  transport = 'FC' AND \"oper_speed\" = 4 AND \"fi_id\" = 'B' ) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"8G\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND  transport = 'FC' AND \"oper_speed\" = 8 AND \"fi_id\" = 'B' ) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"16G\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND  transport = 'FC' AND \"oper_speed\" = 16 AND \"fi_id\" = 'B' ) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"32G\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND  transport = 'FC' AND \"oper_speed\" = 32 AND \"fi_id\" = 'B' ) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A Server Ports - $domain",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND fi_id = 'A') and  $timeFilter group by domain,fi_id,port) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-B Server Ports - $domain",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND fi_id = 'B') and  $timeFilter group by domain,fi_id,port) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A Server Ports - Operational State - $domain",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"UP\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'up' AND \"fi_id\" = 'A') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"SFP not present\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'sfp-not-present' AND \"fi_id\" = 'A') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Admin down\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'admin-down' AND \"fi_id\" = 'A') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Failed\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'failed' AND \"fi_id\" = 'A') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Link Down\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'link-down' AND \"fi_id\" = 'A') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A Server Ports  - Speed - $domain",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"1 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'A' AND \"oper_speed\" = 1) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"10 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'A' AND \"oper_speed\" = 10) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"40 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'A' AND \"oper_speed\" = 40) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"25 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'A' AND \"oper_speed\" = 25) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A Server Ports - Operational State - $domain",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"UP\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'up' AND \"fi_id\" = 'B') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"SFP not present\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'sfp-not-present' AND \"fi_id\" = 'B') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Admin down\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'admin-down' AND \"fi_id\" = 'B') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Failed\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'failed' AND \"fi_id\" = 'B') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"Link Down\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"oper_state\" = 'link-down' AND \"fi_id\" = 'B') and  $timeFilter group by domain,fi_id,port) where  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "FI-A Server Ports  - Speed - $domain",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"1 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'B' AND \"oper_speed\" = 1) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"10 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'B' AND \"oper_speed\" = 10) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"40 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'B' AND \"oper_speed\" = 40) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIServerPortStats",
     "query": "select count(last) AS \"25 Gbps\" from (SELECT last(\"oper_state\") FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^${domain:regex}$/ AND \"channel\" != '' AND \"fi_id\" = 'B' AND \"oper_speed\" = 25) and $timeFilter GROUP BY time($__interval),domain,fi_id,port) where $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "channel", "operator": "!=", "value": " " }
     ]
    }
   ]
  },
  {
   "title": "Servers - $domain",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(model) as \"Model\", last(serial) as \"Serial\", last(num_cpus) as \"# CPU\", last(num_cores) as \"# Cores\", last(memory )as \"Memory\", last(operability) as \"Operability\", last(oper_state) as \"Operational State\", last(oper_state_code) as oper_state_code, last(num_vEths) as \"# vEth\", last(num_vFCs) as \"# vFC\" FROM \"$db\".\"$rp\".\"Servers\" WHERE (\"domain\" =~ /^${domain:regex}$/) AND $timeFilter GROUP BY service_profile,location,domain,chassis,id",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}